/**
 * LaTeX Resume Generator Service
 * 
 * Based on Jake Gutierrez's ATS-friendly resume template
 * Source: https://github.com/sb2nov/resume
 * License: MIT
 * 
 * Generates LaTeX (.tex) files from resume data for ATS-friendly PDF export.
 */

import { ResumeData } from '../types';
import { logger } from '../utils/logger';

// Escape special LaTeX characters
const escapeLatex = (text: string): string => {
  if (!text) return '';
  return text
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/&/g, '\\&')
    .replace(/%/g, '\\%')
    .replace(/\$/g, '\\$')
    .replace(/#/g, '\\#')
    .replace(/_/g, '\\_')
    .replace(/{/g, '\\{')
    .replace(/}/g, '\\}')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');
};

// Format date for display
const formatLatexDate = (date: string): string => {
  if (!date) return '';
  const months = ['Jan.', 'Feb.', 'Mar.', 'Apr.', 'May', 'Jun.', 'Jul.', 'Aug.', 'Sep.', 'Oct.', 'Nov.', 'Dec.'];
  const parts = date.split('-');
  if (parts.length >= 2) {
    const monthIndex = parseInt(parts[1], 10) - 1;
    if (monthIndex >= 0 && monthIndex < 12) {
      return `${months[monthIndex]} ${parts[0]}`;
    }
  }
  return date;
};

// Categorize skills for technical skills section
const categorizeSkills = (allSkills: string[]) => {
  const languages = allSkills.filter(s =>
    /python|java|javascript|typescript|c\+\+|c#|ruby|go|rust|php|swift|kotlin|dart|sql|html|css/i.test(s)
  );
  const tools = allSkills.filter(s =>
    /vs code|eclipse|android studio|xcode|git|docker|kubernetes|jenkins|jira|figma|postman/i.test(s)
  );
  const frameworks = allSkills.filter(s =>
    /react|angular|vue|node|express|django|flask|spring|flutter|next|tailwind|bootstrap/i.test(s)
  );
  const other = allSkills.filter(s =>
    !languages.includes(s) && !tools.includes(s) && !frameworks.includes(s)
  );

  return { languages, tools, frameworks, other };
};

// Generate LaTeX document using Jake Gutierrez's ATS-friendly template
export const generateLatexResume = (data: ResumeData): string => {
  const { personalInfo, summary, experience, education, skills, projects, certifications } = data;

  logger.info('LatexService', 'Generating LaTeX resume', { name: personalInfo.fullName });

  const skillCategories = categorizeSkills(skills);

  // Build sections
  let latex = `%-------------------------
% Resume in LaTeX
% Based on Jake Gutierrez's template (https://github.com/sb2nov/resume)
% Generated by Resume Forge
% License: MIT
%------------------------

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\usepackage{fontawesome5}
\\usepackage{multicol}
\\setlength{\\multicolsep}{-3.0pt}
\\setlength{\\columnsep}{-1pt}
\\input{glyphtounicode}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

% Adjust margins
\\addtolength{\\oddsidemargin}{-0.6in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1.19in}
\\addtolength{\\topmargin}{-.7in}
\\addtolength{\\textheight}{1.4in}

\\urlstyle{same}

\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

% Sections formatting
\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large\\bfseries
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

% Ensure that generated pdf is machine readable/ATS parsable
\\pdfgentounicode=1

%-------------------------
% Custom commands
\\newcommand{\\resumeItem}[1]{
  \\item\\small{
    {#1 \\vspace{-2pt}}
  }
}

\\newcommand{\\classesList}[4]{
    \\item\\small{
        {#1 #2 #3 #4 \\vspace{-2pt}}
  }
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{1.0\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & \\textbf{\\small #2} \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeSubSubheading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\textit{\\small#1} & \\textit{\\small #2} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeProjectHeading}[2]{
    \\item
    \\begin{tabular*}{1.001\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small#1 & \\textbf{\\small #2}\\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeSubItem}[1]{\\resumeItem{#1}\\vspace{-4pt}}

\\renewcommand\\labelitemi{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}
\\renewcommand\\labelitemii{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}

\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.0in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

%-------------------------------------------
%%%%%%  RESUME STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%

\\begin{document}

%----------HEADING----------
\\begin{center}
    {\\Huge \\scshape ${escapeLatex(personalInfo.fullName || 'Your Name')}} \\\\ \\vspace{1pt}
`;

  if (personalInfo.location) {
    latex += `    ${escapeLatex(personalInfo.location)} \\\\ \\vspace{1pt}\n`;
  }

  // Contact info line
  latex += `    \\small `;
  if (personalInfo.phone) {
    latex += `\\raisebox{-0.1\\height}\\faPhone\\ ${escapeLatex(personalInfo.phone)} ~ `;
  }
  if (personalInfo.email) {
    latex += `\\href{mailto:${personalInfo.email}}{\\raisebox{-0.2\\height}\\faEnvelope\\  \\underline{${escapeLatex(personalInfo.email)}}} ~ `;
  }
  if (personalInfo.linkedin) {
    const linkedinClean = personalInfo.linkedin.replace(/^https?:\/\//, '');
    latex += `\\href{https://${linkedinClean}}{\\raisebox{-0.2\\height}\\faLinkedin\\ \\underline{${escapeLatex(linkedinClean)}}} ~ `;
  }
  if (personalInfo.github) {
    const githubClean = personalInfo.github.replace(/^https?:\/\//, '');
    latex += `\\href{https://${githubClean}}{\\raisebox{-0.2\\height}\\faGithub\\ \\underline{${escapeLatex(githubClean)}}}`;
  }
  latex += `
    \\vspace{-8pt}
\\end{center}

`;

  // Education section
  if (education.length > 0) {
    latex += `%-----------EDUCATION-----------
\\section{Education}
  \\resumeSubHeadingListStart
`;
    for (const edu of education) {
      const dateRange = edu.startDate ? `${formatLatexDate(edu.startDate)} -- ${formatLatexDate(edu.graduationYear)}` : formatLatexDate(edu.graduationYear);
      const degreeField = edu.field ? `${escapeLatex(edu.degree)} in ${escapeLatex(edu.field)}` : escapeLatex(edu.degree);
      const cgpaText = edu.cgpa ? `CGPA: ${escapeLatex(edu.cgpa)}` : '';
      latex += `    \\resumeSubheading
      {${escapeLatex(edu.institution)}}{${dateRange}}
      {${degreeField}}{${cgpaText}}
`;
    }
    latex += `  \\resumeSubHeadingListEnd

`;
  }

  // Summary section
  if (summary) {
    latex += `%-----------SUMMARY-----------
\\section{Professional Summary}
\\small{${escapeLatex(summary)}}
\\vspace{-5pt}

`;
  }

  // Experience section
  if (experience.length > 0) {
    latex += `%-----------EXPERIENCE-----------
\\section{Experience}
  \\resumeSubHeadingListStart
`;
    for (const exp of experience) {
      const dateRange = `${formatLatexDate(exp.startDate)} -- ${exp.endDate ? formatLatexDate(exp.endDate) : 'Present'}`;
      latex += `
    \\resumeSubheading
      {${escapeLatex(exp.company)}}{${dateRange}}
      {${escapeLatex(exp.role)}}{${exp.location ? escapeLatex(exp.location) : ''}}
`;
      if (exp.description) {
        latex += `      \\resumeItemListStart\n`;
        const lines = exp.description.split('\n').filter(line => line.trim());
        for (const line of lines) {
          const cleanLine = line.replace(/^[•\-]\s*/, '');
          latex += `        \\resumeItem{${escapeLatex(cleanLine)}}\n`;
        }
        latex += `      \\resumeItemListEnd\n`;
      }
    }
    latex += `  \\resumeSubHeadingListEnd
\\vspace{-16pt}

`;
  }

  // Projects section
  if (projects && projects.length > 0) {
    latex += `%-----------PROJECTS-----------
\\section{Projects}
    \\vspace{-5pt}
    \\resumeSubHeadingListStart
`;
    for (const project of projects) {
      const techStack = (project.techStack || []).join(', ');
      const linkLabel = project.github ? 'GitHub' : (project.link ? 'Live' : '');
      latex += `      \\resumeProjectHeading
          {\\textbf{${escapeLatex(project.name)}} $|$ \\emph{${escapeLatex(techStack)}}}{${linkLabel}}
`;
      if (project.description) {
        latex += `          \\resumeItemListStart\n`;
        const lines = project.description.split('\n').filter(line => line.trim());
        for (const line of lines) {
          const cleanLine = line.replace(/^[•\-]\s*/, '');
          latex += `            \\resumeItem{${escapeLatex(cleanLine)}}\n`;
        }
        latex += `          \\resumeItemListEnd
          \\vspace{-13pt}\n`;
      }
    }
    latex += `    \\resumeSubHeadingListEnd
\\vspace{-15pt}

`;
  }

  // Technical Skills section
  if (skills.length > 0) {
    latex += `%-----------TECHNICAL SKILLS-----------
\\section{Technical Skills}
 \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
`;
    if (skillCategories.languages.length > 0) {
      latex += `     \\textbf{Languages}{: ${escapeLatex(skillCategories.languages.join(', '))}} \\\\\n`;
    }
    if (skillCategories.tools.length > 0) {
      latex += `     \\textbf{Developer Tools}{: ${escapeLatex(skillCategories.tools.join(', '))}} \\\\\n`;
    }
    if (skillCategories.frameworks.length > 0) {
      latex += `     \\textbf{Technologies/Frameworks}{: ${escapeLatex(skillCategories.frameworks.join(', '))}} \\\\\n`;
    }
    if (skillCategories.other.length > 0) {
      latex += `     \\textbf{Other Skills}{: ${escapeLatex(skillCategories.other.join(', '))}}\n`;
    }
    latex += `    }}
 \\end{itemize}
 \\vspace{-16pt}

`;
  }

  // Certifications section
  if (certifications && certifications.length > 0) {
    latex += `%-----------CERTIFICATIONS-----------
\\section{Certifications}
    \\resumeSubHeadingListStart
`;
    for (const cert of certifications) {
      const dateText = cert.date ? formatLatexDate(cert.date) : '';
      const issuerText = cert.issuer ? escapeLatex(cert.issuer) : '';
      const idText = cert.credentialId ? `ID: ${escapeLatex(cert.credentialId)}` : '';
      latex += `        \\resumeSubheading
          {${escapeLatex(cert.name)}}{${dateText}}
          {${issuerText}}{${idText}}
`;
    }
    latex += `    \\resumeSubHeadingListEnd

`;
  }

  // End document
  latex += `%-------------------------------------------
\\end{document}
`;

  return latex;
};

// Download LaTeX file
export const downloadLatex = (data: ResumeData, filename: string = 'resume'): void => {
  logger.info('LatexService', 'Downloading LaTeX file', { filename });
  const latex = generateLatexResume(data);
  const blob = new Blob([latex], { type: 'application/x-latex' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.tex`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  logger.info('LatexService', 'LaTeX file downloaded successfully');
};

export default { generateLatexResume, downloadLatex };
