/**
 * LaTeX Resume Generator Service
 * 
 * Based on Jake Gutierrez's ATS-friendly resume template
 * Source: https://github.com/sb2nov/resume
 * License: MIT
 * 
 * Generates LaTeX (.tex) files from resume data for ATS-friendly PDF export.
 */

import { ResumeData } from '../types';
import { logger } from '../utils/logger';

// Escape special LaTeX characters
const escapeLatex = (text: string): string => {
  if (!text) return '';
  return text
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/&/g, '\\&')
    .replace(/%/g, '\\%')
    .replace(/\$/g, '\\$')
    .replace(/#/g, '\\#')
    .replace(/_/g, '\\_')
    .replace(/{/g, '\\{')
    .replace(/}/g, '\\}')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');
};

// Format date for display
const formatLatexDate = (date: string): string => {
  if (!date) return '';
  const months = ['Jan.', 'Feb.', 'Mar.', 'Apr.', 'May', 'Jun.', 'Jul.', 'Aug.', 'Sep.', 'Oct.', 'Nov.', 'Dec.'];
  const parts = date.split('-');
  if (parts.length >= 2) {
    const monthIndex = parseInt(parts[1], 10) - 1;
    if (monthIndex >= 0 && monthIndex < 12) {
      return `${months[monthIndex]} ${parts[0]}`;
    }
  }
  return date;
};

// Extract username from URL
const extractUsername = (url: string, patterns: RegExp[]): string => {
  let result = url;
  for (const pattern of patterns) {
    result = result.replace(pattern, '');
  }
  return result.replace(/\/$/, '').split('/')[0] || url;
};

// Generate LaTeX document using Jake Gutierrez's ATS-friendly template
export const generateLatexResume = (data: ResumeData): string => {
  const { personalInfo, summary, experience, education, skills, skillsData, projects, vocationalCertifications, achievements, extracurricular, showDeclaration } = data;

  logger.info('LatexService', 'Generating LaTeX resume', { name: personalInfo.fullName });

  // Build sections
  let latex = `%-------------------------
% Resume in LaTeX
% Based on Jake Gutierrez's template (https://github.com/sb2nov/resume)
% Generated by Resume Forge
% License: MIT
%------------------------

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\usepackage{fontawesome5}
\\usepackage{multicol}
\\setlength{\\multicolsep}{-3.0pt}
\\setlength{\\columnsep}{-1pt}
\\input{glyphtounicode}

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

% Adjust margins
\\addtolength{\\oddsidemargin}{-0.6in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1.19in}
\\addtolength{\\topmargin}{-.7in}
\\addtolength{\\textheight}{1.4in}

\\urlstyle{same}

\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

% Sections formatting
\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large\\bfseries
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

% Ensure that generated pdf is machine readable/ATS parsable
\\pdfgentounicode=1

%-------------------------
% Custom commands
\\newcommand{\\resumeItem}[1]{
  \\item\\small{
    {#1 \\vspace{-2pt}}
  }
}

\\newcommand{\\classesList}[4]{
    \\item\\small{
        {#1 #2 #3 #4 \\vspace{-2pt}}
  }
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{1.0\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & \\textbf{\\small #2} \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeSubSubheading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\textit{\\small#1} & \\textit{\\small #2} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeProjectHeading}[2]{
    \\item
    \\begin{tabular*}{1.001\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small#1 & \\textbf{\\small #2}\\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeSubItem}[1]{\\resumeItem{#1}\\vspace{-4pt}}

\\renewcommand\\labelitemi{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}
\\renewcommand\\labelitemii{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}

\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.0in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

%-------------------------------------------
%%%%%%  RESUME STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%

\\begin{document}

%----------HEADING----------
\\begin{center}
    {\\Huge \\scshape ${escapeLatex(personalInfo.fullName || 'Your Name')}} \\\\ \\vspace{1pt}
`;

  if (personalInfo.location) {
    latex += `    ${escapeLatex(personalInfo.location)} \\\\ \\vspace{1pt}\n`;
  }

  // Contact info line 1: Phone, Email, GitHub, LinkedIn (text labels with pipe separators)
  const contactParts: string[] = [];

  if (personalInfo.phone) {
    const phoneNumber = personalInfo.phone.replace(/[^+\d]/g, '');
    contactParts.push(`\\textbf{Phone:} \\href{tel:${phoneNumber}}{\\underline{${escapeLatex(personalInfo.phone)}}}`);
  }
  if (personalInfo.email) {
    contactParts.push(`\\textbf{Mail:} \\href{mailto:${personalInfo.email}}{\\underline{${escapeLatex(personalInfo.email)}}}`);
  }
  if (personalInfo.github) {
    const ghUser = personalInfo.githubUsername || extractUsername(personalInfo.github, [/^https?:\/\/(www\.)?github\.com\//]);
    const ghUrl = personalInfo.github.startsWith('http') ? personalInfo.github : `https://github.com/${personalInfo.github}`;
    contactParts.push(`\\textbf{GitHub:} \\href{${ghUrl}}{\\underline{@${escapeLatex(ghUser)}}}`);
  }
  if (personalInfo.linkedin) {
    const liUser = personalInfo.linkedinUsername || extractUsername(personalInfo.linkedin, [/^https?:\/\/(www\.)?linkedin\.com\/in\//]);
    const liUrl = personalInfo.linkedin.startsWith('http') ? personalInfo.linkedin : `https://linkedin.com/in/${personalInfo.linkedin}`;
    contactParts.push(`\\textbf{LinkedIn:} \\href{${liUrl}}{\\underline{@${escapeLatex(liUser)}}}`);
  }

  if (contactParts.length > 0) {
    latex += `    \\small ${contactParts.join(' $|$ ')}\n`;
  }

  // Contact info line 2: Competitive programming profiles (text labels with pipe separators)
  const competitiveParts: string[] = [];

  if (personalInfo.leetcode) {
    const lcUser = personalInfo.leetcodeUsername || extractUsername(personalInfo.leetcode, [/^https?:\/\/(www\.)?leetcode\.com\/(u\/)?/]);
    const lcRating = personalInfo.leetcodeRating ? ` (${personalInfo.leetcodeRating})` : '';
    competitiveParts.push(`\\textbf{LeetCode:} \\href{https://leetcode.com/u/${lcUser}}{\\underline{@${escapeLatex(lcUser)}${escapeLatex(lcRating)}}}`);
  }
  if (personalInfo.codeforces) {
    const cfUser = personalInfo.codeforcesUsername || extractUsername(personalInfo.codeforces, [/^https?:\/\/(www\.)?codeforces\.com\/profile\//]);
    const cfRating = personalInfo.codeforcesRating ? ` (${personalInfo.codeforcesRating})` : '';
    competitiveParts.push(`\\textbf{Codeforces:} \\href{https://codeforces.com/profile/${cfUser}}{\\underline{@${escapeLatex(cfUser)}${escapeLatex(cfRating)}}}`);
  }
  if (personalInfo.codechef) {
    const ccUser = personalInfo.codechefUsername || extractUsername(personalInfo.codechef, [/^https?:\/\/(www\.)?codechef\.com\/users\//]);
    const ccRating = personalInfo.codechefRating ? ` (${personalInfo.codechefRating})` : '';
    competitiveParts.push(`\\textbf{CodeChef:} \\href{https://www.codechef.com/users/${ccUser}}{\\underline{@${escapeLatex(ccUser)}${escapeLatex(ccRating)}}}`);
  }
  if (personalInfo.website) {
    const wsDisplay = personalInfo.website.replace(/^https?:\/\//, '');
    const wsUrl = personalInfo.website.startsWith('http') ? personalInfo.website : `https://${personalInfo.website}`;
    competitiveParts.push(`\\textbf{Portfolio:} \\href{${wsUrl}}{\\underline{${escapeLatex(wsDisplay)}}}`);
  }

  if (competitiveParts.length > 0) {
    latex += `    \\\\ \\footnotesize ${competitiveParts.join(' $|$ ')}\n`;
  }

  latex += `    \\vspace{-8pt}
\\end{center}

`;

  // Summary section
  if (summary) {
    latex += `%-----------SUMMARY-----------
\\section{Summary}
\\small{${escapeLatex(summary)}}
\\vspace{-5pt}

`;
  }

  // Education section
  if (education.length > 0) {
    latex += `%-----------EDUCATION-----------
\\section{Education}
  \\resumeSubHeadingListStart
`;
    for (const edu of education) {
      const dateRange = edu.startDate ? `${formatLatexDate(edu.startDate)} -- ${formatLatexDate(edu.graduationYear)}` : formatLatexDate(edu.graduationYear);
      const degreeField = edu.field ? `${escapeLatex(edu.degree)} in ${escapeLatex(edu.field)}` : escapeLatex(edu.degree);
      const cgpaText = edu.cgpa ? `CGPA: ${escapeLatex(edu.cgpa)}` : '';
      latex += `    \\resumeSubheading
      {${escapeLatex(edu.institution)}}{${dateRange}}
      {${degreeField}}{${cgpaText}}
`;
    }
    latex += `  \\resumeSubHeadingListEnd

`;
  }

  // Vocational Certifications section
  if (vocationalCertifications && vocationalCertifications.length > 0) {
    latex += `%-----------VOCATIONAL CERTIFICATIONS-----------
\\section{Vocational Certifications}
  \\resumeSubHeadingListStart
`;
    for (const cert of vocationalCertifications) {
      const dateText = cert.date ? formatLatexDate(cert.date) : '';
      latex += `    \\resumeSubheading
      {${escapeLatex(cert.name)}}{${dateText}}
      {\\textit{${escapeLatex(cert.provider)}}}{}
`;
      if (cert.description) {
        latex += `      \\resumeItemListStart\n`;
        const lines = cert.description.split('\n').filter(line => line.trim());
        for (const line of lines) {
          const cleanLine = line.replace(/^[•\-]\s*/, '');
          latex += `        \\resumeItem{${escapeLatex(cleanLine)}}\n`;
        }
        latex += `      \\resumeItemListEnd\n`;
      }
    }
    latex += `  \\resumeSubHeadingListEnd

`;
  }

  // Skills section - use skillsData if available, otherwise fall back to skills array
  const hasSkillsData = skillsData && Object.values(skillsData).some(arr => arr && arr.length > 0);

  if (hasSkillsData || skills.length > 0) {
    latex += `%-----------TECHNICAL SKILLS-----------
\\section{Skills}
 \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
`;
    if (hasSkillsData) {
      if (skillsData?.coursework && skillsData.coursework.length > 0) {
        latex += `     \\textbf{Coursework}{: ${escapeLatex(skillsData.coursework.join(', '))}} \\\\\n`;
      }
      if (skillsData?.programmingLanguages && skillsData.programmingLanguages.length > 0) {
        latex += `     \\textbf{Programming Languages}{: ${escapeLatex(skillsData.programmingLanguages.join(', '))}} \\\\\n`;
      }
      if (skillsData?.webTechnologies && skillsData.webTechnologies.length > 0) {
        latex += `     \\textbf{Web Technologies}{: ${escapeLatex(skillsData.webTechnologies.join(', '))}} \\\\\n`;
      }
      if (skillsData?.databases && skillsData.databases.length > 0) {
        latex += `     \\textbf{Databases}{: ${escapeLatex(skillsData.databases.join(', '))}} \\\\\n`;
      }
      if (skillsData?.tools && skillsData.tools.length > 0) {
        latex += `     \\textbf{Tools}{: ${escapeLatex(skillsData.tools.join(', '))}} \\\\\n`;
      }
      if (skillsData?.languages && skillsData.languages.length > 0) {
        latex += `     \\textbf{Languages}{: ${escapeLatex(skillsData.languages.join(', '))}} \\\\\n`;
      }
      if (skillsData?.interests && skillsData.interests.length > 0) {
        latex += `     \\textbf{Interests}{: ${escapeLatex(skillsData.interests.join(', '))}}\n`;
      }
    } else {
      // Fallback to flat skills array
      latex += `     \\textbf{Skills}{: ${escapeLatex(skills.join(', '))}}\n`;
    }
    latex += `    }}
 \\end{itemize}
 \\vspace{-5pt}

`;
  }

  // Experience section
  if (experience.length > 0) {
    latex += `%-----------EXPERIENCE-----------
\\section{Experience}
  \\resumeSubHeadingListStart
`;
    for (const exp of experience) {
      const dateRange = `${formatLatexDate(exp.startDate)} -- ${exp.endDate ? formatLatexDate(exp.endDate) : 'Present'}`;
      latex += `
    \\resumeSubheading
      {${escapeLatex(exp.company)}}{${dateRange}}
      {${escapeLatex(exp.role)}}{${exp.location ? escapeLatex(exp.location) : ''}}
`;
      if (exp.description) {
        latex += `      \\resumeItemListStart\n`;
        const lines = exp.description.split('\n').filter(line => line.trim());
        for (const line of lines) {
          const cleanLine = line.replace(/^[•\-]\s*/, '');
          latex += `        \\resumeItem{${escapeLatex(cleanLine)}}\n`;
        }
        latex += `      \\resumeItemListEnd\n`;
      }
    }
    latex += `  \\resumeSubHeadingListEnd
\\vspace{-16pt}

`;
  }

  // Projects section
  if (projects && projects.length > 0) {
    latex += `%-----------PROJECTS-----------
\\section{Projects}
    \\vspace{-5pt}
    \\resumeSubHeadingListStart
`;
    for (const project of projects) {
      const techStack = (project.techStack || []).join(', ');
      let links = '';
      if (project.github) {
        links += `\\href{${project.github}}{\\underline{GitHub}}`;
      }
      if (project.link) {
        if (links) links += ' $|$ ';
        links += `\\href{${project.link}}{\\underline{Visit Site}}`;
      }
      latex += `      \\resumeProjectHeading
          {\\textbf{${escapeLatex(project.name)}} $|$ \\emph{${escapeLatex(techStack)}}}{${links}}
`;
      if (project.description) {
        latex += `          \\resumeItemListStart\n`;
        const lines = project.description.split('\n').filter(line => line.trim());
        for (const line of lines) {
          const cleanLine = line.replace(/^[•\-]\s*/, '');
          latex += `            \\resumeItem{${escapeLatex(cleanLine)}}\n`;
        }
        latex += `          \\resumeItemListEnd
          \\vspace{-13pt}\n`;
      }
    }
    latex += `    \\resumeSubHeadingListEnd
\\vspace{-5pt}

`;
  }

  // Achievements section
  if (achievements && achievements.length > 0) {
    latex += `%-----------ACHIEVEMENTS-----------
\\section{Achievements}
  \\resumeSubHeadingListStart
`;
    for (const ach of achievements) {
      const dateText = ach.date ? formatLatexDate(ach.date) : '';
      const org = ach.organization ? escapeLatex(ach.organization) : '';
      latex += `    \\resumeSubheading
      {${escapeLatex(ach.title)}}{${dateText}}
      {\\textit{${org}}}{}
`;
      if (ach.description) {
        latex += `      \\resumeItemListStart\n`;
        const lines = ach.description.split('\n').filter(line => line.trim());
        for (const line of lines) {
          const cleanLine = line.replace(/^[•\-]\s*/, '');
          latex += `        \\resumeItem{${escapeLatex(cleanLine)}}\n`;
        }
        latex += `      \\resumeItemListEnd\n`;
      }
    }
    latex += `  \\resumeSubHeadingListEnd

`;
  }

  // Extracurricular Activities section
  if (extracurricular && extracurricular.length > 0) {
    latex += `%-----------EXTRACURRICULAR ACTIVITIES-----------
\\section{Extracurricular Activities}
  \\resumeSubHeadingListStart
`;
    for (const ext of extracurricular) {
      const startDate = ext.startDate ? formatLatexDate(ext.startDate) : '';
      const endDate = ext.isCurrent ? 'Present' : (ext.endDate ? formatLatexDate(ext.endDate) : '');
      const dateRange = startDate ? `${startDate} -- ${endDate}` : endDate;

      latex += `    \\resumeSubheading
      {${escapeLatex(ext.organization)}}{${dateRange}}
      {${escapeLatex(ext.role)}}{}
`;
      if (ext.description) {
        latex += `      \\resumeItemListStart\n`;
        const lines = ext.description.split('\n').filter(line => line.trim());
        for (const line of lines) {
          const cleanLine = line.replace(/^[•\-]\s*/, '');
          latex += `        \\resumeItem{${escapeLatex(cleanLine)}}\n`;
        }
        latex += `      \\resumeItemListEnd\n`;
      }
    }
    latex += `  \\resumeSubHeadingListEnd

`;
  }

  // Declaration section
  if (showDeclaration) {
    latex += `%-----------DECLARATION-----------
\\section{Declaration}
\\small{I hereby declare that all the details furnished above are true to the best of my knowledge and belief.}
\\vspace{-5pt}

`;
  }

  // End document
  latex += `%-------------------------------------------
\\end{document}
`;

  return latex;
};

// Download LaTeX file
export const downloadLatex = (data: ResumeData, filename: string = 'resume'): void => {
  logger.info('LatexService', 'Downloading LaTeX file', { filename });
  const latex = generateLatexResume(data);
  const blob = new Blob([latex], { type: 'application/x-latex' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.tex`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  logger.info('LatexService', 'LaTeX file downloaded successfully');
};

// Compile LaTeX to PDF using free API (latex.ytotech.com)
export const compileLatexToPDF = async (latex: string): Promise<Blob> => {
  logger.info('LatexService', 'Compiling LaTeX to PDF via API');

  const response = await fetch('https://latex.ytotech.com/builds/sync', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      compiler: 'pdflatex',
      resources: [{
        main: true,
        content: latex
      }]
    })
  });

  if (!response.ok) {
    const errorText = await response.text().catch(() => 'Unknown error');
    logger.error('LatexService', 'LaTeX compilation failed', { status: response.status, error: errorText });
    throw new Error(`LaTeX compilation failed: ${response.status}`);
  }

  logger.info('LatexService', 'LaTeX compiled successfully');
  return response.blob();
};

// Generate and download PDF from resume data
export const downloadLatexPDF = async (data: ResumeData, filename: string = 'resume'): Promise<void> => {
  logger.info('LatexService', 'Generating PDF from resume data', { filename });

  // Generate LaTeX code
  const latex = generateLatexResume(data);

  // Compile to PDF
  const pdfBlob = await compileLatexToPDF(latex);

  // Download the PDF
  const url = URL.createObjectURL(pdfBlob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  logger.info('LatexService', 'PDF downloaded successfully');
};

export default { generateLatexResume, downloadLatex, compileLatexToPDF, downloadLatexPDF };
